# - name: Setup deb.sury.org repository - Add GPG key
#   get_url:
#     url: https://packages.sury.org/php/apt.gpg
#     dest: /etc/apt/trusted.gpg.d/php-sury.gpg
#     mode: "0644"
#
# - name: Setup deb.sury.org repository - Install apt-transport-https
#   apt:
#     state: present
#     name: apt-transport-https
#
# - name: Setup deb.sury.org repository - Add source list
#   copy:
#     dest: /etc/apt/sources.list.d/php-sury.list
#     force: no
#     mode: "0600"
#     content: |
#         deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main


# Add php sury repository from PPA and install its signing key.
# On Ubuntu target:
- name: Adding PPA for PHP Sury Ubuntu
  apt_repository:
    repo: ppa:ondrej/php
